# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Version Check

on:
  workflow_dispatch:

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Print Node.js version
        run: node -v
