name: build-and-push-docker

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: workflow-java
  DOCKER_HUB_USERNAME: xamflex6
  JAVA_VERSION: '17'

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      
      - name: Configuration du JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          
      - name: Compilation avec Gradle
        # On entre dans le dossier du projet pour trouver le wrapper Gradle
        run: |
          cd Projet_G_Actions_Tricarico
          chmod +x gradlew
          ./gradlew bootJar -x test

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Construction et Push Docker
        uses: docker/build-push-action@v5
        with:
          # On indique à Docker que tout se passe dans le sous-dossier
          context: ./Projet_G_Actions_Tricarico
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
