name: build-and-push-docker

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: workflow-java # Corrigé : pas d'espace
  DOCKER_HUB_USERNAME: xamflex6
  JAVA_VERSION: '17' 

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      
      - name: Configuration du JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          
      - name: Compilation avec Gradle
        # On donne les droits d'exécution et on compile le JAR
        run: |
          chmod +x gradlew
          ./gradlew bootJar -x test

      - name: Récupération du SHA court pour le tag
        id: docker_tag
        run: echo "SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_OUTPUT
      
      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }} # Doit être dans l'onglet SECRETS
          
      - name: Construction et Push de l'image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.docker_tag.outputs.SHA_SHORT }}
